apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-docker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-docker-pod
  template:
    metadata:
      labels:
        app: mongo-docker-pod
    spec:
      containers:
        - name: mongo-docker-container
          image: dockerstrange101/backend:tag1
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongo-docker-pod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001
  externalIPs:
    - 10.9.8.7
